Repository mosn/extensions, pull requests merged in 2021-12, with the labels that each got.

#3 Update README.md
  README.md
Labels: cla:yes, size/XS

#6 modify streamfilter demo
  go-plugin/configs/streamfilters/auth/mosn_config.json
  go-plugin/plugins/streamfilters/auth/main/auth.go
Labels: cla:yes, size/XS

#9 support ant plugin debugging.
  go-plugin/Makefile
  go-plugin/configs/codecs/bolt/metadata.json
  go-plugin/configs/codecs/xr/metadata.json
  go-plugin/etc/ant/env_conf
  go-plugin/etc/ant/run.sh
  go-plugin/etc/ant/start.sh
  go-plugin/etc/ant/stop.sh
  go-plugin/etc/script/compile.sh
  go-plugin/etc/script/run.sh
Labels: cla:yes, size/L

#11 support build multiple plugins.
  go-plugin/Makefile
  go-plugin/README.md
  go-plugin/etc/script/compile-codec.sh
  go-plugin/etc/script/compile-filter.sh
  go-plugin/etc/script/compile-transcoder.sh
  go-plugin/go.sum
Labels: cla:yes, size/M

#12 rename stream_filters.
  go-plugin/Makefile
  go-plugin/configs/codecs/bolt/egress_bolt.json
  go-plugin/configs/codecs/bolt/ingress_bolt.json
  go-plugin/configs/codecs/dubbo/egress_dubbo.json
  go-plugin/configs/codecs/dubbo/ingress_dubbo.json
  go-plugin/configs/codecs/xr/egress_xr.json
  go-plugin/configs/codecs/xr/ingress_xr.json
  go-plugin/configs/stream_filters/auth/egress_config.json
  go-plugin/configs/stream_filters/auth/metadata.json
  go-plugin/configs/stream_filters/auth/mosn_config.json
  go-plugin/etc/script/compile-codec.sh
  go-plugin/etc/script/compile-filter.sh
  go-plugin/etc/script/compile.sh
  go-plugin/etc/script/run.sh
  go-plugin/plugins/stream_filters/auth/VERSION
  go-plugin/plugins/stream_filters/auth/main/auth.go
  go-plugin/plugins/transcoders/xr2sp/main/xr2sp.go
Labels: cla:yes, size/L

#13 clean logs when start sidecar.
  go-plugin/etc/ant/start.sh
Labels: question, cla:yes, size/XS

#14 fix test case.
  go-plugin/pkg/protocol/bolt/matcher_test.go
Labels: bug, cla:yes, size/XS

#15 update container port.
  go-plugin/configs/codecs/sp/egress_sp.json
  go-plugin/configs/codecs/sp/ingress_sp.json
  go-plugin/configs/codecs/sp/metadata.json
  go-plugin/etc/ant/start.sh
  go-plugin/go.sum
  go-plugin/plugins/codecs/sp/main/codec.go
Labels: cla:yes, size/L

#16 update sp data-id.
  go-plugin/configs/codecs/sp/metadata.json
Labels: cla:yes, size/XS

#17 update dlv image.
  go-plugin/.gitignore
  go-plugin/build/image/Dockerfile
  go-plugin/etc/script/compile.sh
Labels: cla:yes, size/S

#18 read address from env.
  go-plugin/etc/ant/env_conf
Labels: cla:yes, size/XS

#19 modify xr2sp dubbo
  go-plugin/configs/codecs/xr/metadata.json
  go-plugin/configs/transcoders/xr2sp/egress_config.json
  go-plugin/pkg/protocol/dubbo/common/cloud_util.go
  go-plugin/pkg/protocol/dubbo/constants/alipay_router_constants.go
  go-plugin/pkg/protocol/dubbo/govern_util/govern_utils.go
  go-plugin/pkg/protocol/dubbo/govern_util/key.go
  go-plugin/plugins/transcoders/xr2sp/main/xr2sp.go
Labels: cla:yes, size/L

#20 fix metadata config.
  go-plugin/configs/codecs/bolt/metadata.json
  go-plugin/configs/codecs/xr/metadata.json
  go-plugin/pkg/protocol/xr/protocol.go
Labels: bug, cla:yes, size/XS

#21 stop container if run make.
  go-plugin/Makefile
  go-plugin/etc/ant/stop.sh
  go-plugin/etc/script/stop.sh
Labels: cla:yes, size/M

#22 run apt install tcpdump
  go-plugin/build/image/Dockerfile
Labels: cla:yes, size/XS

#23 support package plugin.
  go-plugin/Makefile
  go-plugin/build/image/Dockerfile
  go-plugin/configs/codecs/bolt/metadata.json
  go-plugin/configs/codecs/dubbo/metadata.json
  go-plugin/configs/codecs/sp/metadata.json
  go-plugin/configs/codecs/xr/metadata.json
  go-plugin/configs/stream_filters/auth/metadata.json
  go-plugin/configs/transcoders/xr2sp/metadata.json
  go-plugin/etc/script/compile.sh
  go-plugin/etc/script/package-codec.sh
  go-plugin/etc/script/package-filter.sh
  go-plugin/etc/script/package-transcoder.sh
Labels: cla:yes, size/L

#25 fix xr transcoder bugs.
  go-plugin/configs/transcoders/xr2sp/egress_config.json
  go-plugin/etc/ant/start.sh
  go-plugin/etc/script/start.sh
  go-plugin/plugins/transcoders/xr2sp/main/xr2sp.go
Labels: bug, cla:yes, size/XS

#24 support transcoder plugin: sp2dubbo, dubbo2sp
  go-plugin/configs/codecs/dubbo/metadata.json
  go-plugin/configs/transcoders/dubbo2sp/egress_config.json
  go-plugin/configs/transcoders/dubbo2sp/metadata.json
  go-plugin/configs/transcoders/sp2dubbo/egress_config.json
  go-plugin/configs/transcoders/sp2dubbo/metadata.json
  go-plugin/pkg/protocol/dubbo/decoder.go
  go-plugin/pkg/protocol/dubbo/encoder.go
  go-plugin/pkg/protocol/dubbo/types.go
  go-plugin/plugins/transcoders/dubbo2sp/VERSION
  go-plugin/plugins/transcoders/dubbo2sp/main/dubbo2sp.go
  go-plugin/plugins/transcoders/sp2dubbo/VERSION
  go-plugin/plugins/transcoders/sp2dubbo/main/sp2dubbo.go
Labels: cla:yes, size/XL

#26 Bolt to http
  go-plugin/configs/codecs/bolt/egress_bolt.json
  go-plugin/configs/codecs/bolt/ingress_bolt.json
  go-plugin/configs/codecs/bolt/metadata.json
  go-plugin/configs/codecs/dubbo/egress_dubbo.json
  go-plugin/configs/codecs/dubbo/ingress_dubbo.json
  go-plugin/configs/codecs/sp/egress_sp.json
  go-plugin/configs/codecs/sp/ingress_sp.json
  go-plugin/configs/codecs/sp/metadata.json
  go-plugin/configs/codecs/xr/egress_xr.json
  go-plugin/configs/codecs/xr/ingress_xr.json
  go-plugin/configs/transcoders/bolt2sp/egress_config.json
  go-plugin/configs/transcoders/bolt2sp/metadata.json
  go-plugin/pkg/protocol/bolt/types.go
  go-plugin/plugins/transcoders/bolt2sp/VERSION
  go-plugin/plugins/transcoders/bolt2sp/main/bolt2sp.go
  go-plugin/plugins/transcoders/bolt2sp/main/bolt2sp_test.go
Labels: cla:yes, size/L

#27 feat: add seriver name
  go-plugin/configs/codecs/bolt/metadata.json
  go-plugin/configs/codecs/sp/metadata.json
  go-plugin/configs/transcoders/bolt2sp/egress_config.json
  go-plugin/plugins/transcoders/bolt2sp/main/bolt2sp.go
  go-plugin/plugins/transcoders/bolt2sp/main/bolt2sp_test.go
Labels: cla:yes, size/L

#28 modify sp2dubbo、dubbo2sp plugin：support http query, body
  go-plugin/configs/transcoders/dubbo2sp/egress_config.json
  go-plugin/configs/transcoders/dubbo2sp/metadata.json
  go-plugin/configs/transcoders/sp2dubbo/egress_config.json
  go-plugin/configs/transcoders/sp2dubbo/metadata.json
  go-plugin/plugins/transcoders/dubbo2sp/main/dubbo2sp.go
  go-plugin/plugins/transcoders/sp2dubbo/main/sp2dubbo.go
Labels: cla:yes, size/L

#29 add health check config.
  go-plugin/configs/codecs/xr/metadata.json
  go-plugin/etc/ant/start.sh
  go-plugin/etc/script/start.sh
Labels: cla:yes, size/S

#30 feat: fix transcoder
  go-plugin/configs/transcoders/bolt2sp/egress_config.json
  go-plugin/configs/transcoders/dubbo2sp/egress_config.json
  go-plugin/configs/transcoders/sp2dubbo/egress_config.json
  go-plugin/configs/transcoders/xr2sp/egress_config.json
  go-plugin/go.mod
  go-plugin/go.sum
  go-plugin/pkg/protocol/bolt/mapping.go
  go-plugin/pkg/protocol/bolt/matcher.go
  go-plugin/pkg/protocol/bolt/matcher_test.go
  go-plugin/pkg/protocol/bolt/protocol.go
  go-plugin/pkg/protocol/dubbo/mapping.go
  go-plugin/pkg/protocol/dubbo/matcher.go
  go-plugin/pkg/protocol/dubbo/protocol.go
  go-plugin/plugins/codecs/bolt/main/codec.go
  go-plugin/plugins/codecs/dubbo/main/codec.go
  go-plugin/vendor/github.com/klauspost/compress/LICENSE
  go-plugin/vendor/github.com/klauspost/compress/flate/inflate.go
  go-plugin/vendor/github.com/klauspost/compress/flate/regmask_other.go
  go-plugin/vendor/github.com/klauspost/compress/gzip/gunzip.go
  go-plugin/vendor/github.com/klauspost/compress/zlib/reader.go
  go-plugin/vendor/github.com/rcrowley/go-metrics/.travis.yml
  go-plugin/vendor/github.com/valyala/fasthttp/.gitignore
  go-plugin/vendor/github.com/valyala/fasthttp/README.md
  go-plugin/vendor/github.com/valyala/fasthttp/args.go
  go-plugin/vendor/github.com/valyala/fasthttp/bytesconv.go
  go-plugin/vendor/github.com/valyala/fasthttp/bytesconv_32.go
  go-plugin/vendor/github.com/valyala/fasthttp/bytesconv_64.go
  go-plugin/vendor/github.com/valyala/fasthttp/client.go
  go-plugin/vendor/github.com/valyala/fasthttp/cookie.go
  go-plugin/vendor/github.com/valyala/fasthttp/go.mod
  go-plugin/vendor/github.com/valyala/fasthttp/go.sum
  go-plugin/vendor/github.com/valyala/fasthttp/header.go
  go-plugin/vendor/github.com/valyala/fasthttp/http.go
  go-plugin/vendor/github.com/valyala/fasthttp/server.go
  go-plugin/vendor/github.com/valyala/fasthttp/status.go
  go-plugin/vendor/github.com/valyala/fasthttp/strings.go
  go-plugin/vendor/github.com/valyala/fasthttp/tcpdialer.go
  go-plugin/vendor/github.com/valyala/fasthttp/uri.go
  go-plugin/vendor/github.com/valyala/fasthttp/uri_unix.go
  go-plugin/vendor/github.com/valyala/fasthttp/uri_windows.go
  go-plugin/vendor/github.com/valyala/fasthttp/userdata.go
  go-plugin/vendor/modules.txt
  go-plugin/vendor/mosn.io/api/network.go
  go-plugin/vendor/mosn.io/api/route.go
  go-plugin/vendor/mosn.io/api/stream_filter.go
  go-plugin/vendor/mosn.io/api/xprotocol.go
Labels: bug, cla:yes, size/XXL
