Repository mosn/extensions, pull requests merged in 2022-05, with the labels that each got.

#114 remove build path dependency & fix debug image error
  go-plugin/Makefile
  go-plugin/etc/ant/start.sh
  go-plugin/etc/script/env_conf
  go-plugin/etc/script/run.sh
  go-plugin/etc/script/start.sh
  go-plugin/etc/script/stop.sh
Labels: bug, cla:yes, size/L

#115 feat: support hijack
  go-plugin/configs/codecs/http/egress_http.json
  go-plugin/configs/codecs/http/ingress_http.json
  go-plugin/configs/codecs/http/metadata.json
  go-plugin/configs/codecs/http/test.sh
  go-plugin/plugins/codecs/http/main/codec.go
Labels: cla:yes, size/L

#116 新增服务治理文档
  go-plugin/README.md
  go-plugin/doc/2.7.1ratelimit.md
  go-plugin/doc/2.7.2fusing.md
  go-plugin/doc/2.7.3downgrade.md
  go-plugin/doc/2.7.4fault-inject.md
  go-plugin/doc/2.7.5route.md
  go-plugin/doc/2.7.6fault-isolation.md
  go-plugin/doc/2.7.7governance-key.md
  go-plugin/doc/images/downgrade-client-config-caller.png
  go-plugin/doc/images/downgrade-client-config.png
  go-plugin/doc/images/downgrade-config.png
  go-plugin/doc/images/downgrade-theory.png
  go-plugin/doc/images/fault-inject-client-config-caller.png
  go-plugin/doc/images/fault-inject-client-config.png
  go-plugin/doc/images/fault-inject-config.png
  go-plugin/doc/images/fault-inject-server-config-caller.png
  go-plugin/doc/images/fault-inject-server-config.png
  go-plugin/doc/images/fault-isolation-client-config-caller-1.png
  go-plugin/doc/images/fault-isolation-client-config-caller-2.png
  go-plugin/doc/images/fault-isolation-client-config-caller-3.png
  go-plugin/doc/images/fault-isolation-client-config.png
  go-plugin/doc/images/fault-isolation-config.png
  go-plugin/doc/images/fusing-config.png
  go-plugin/doc/images/fusing-server-config-1.png
  go-plugin/doc/images/fusing-server-config-2.png
  go-plugin/doc/images/fusing-server-config-caller-1.png
  go-plugin/doc/images/fusing-server-config-caller-2.png
  go-plugin/doc/images/fusing-server-config-rt-1.png
  go-plugin/doc/images/fusing-server-config-rt-2.png
  go-plugin/doc/images/fusing-server-config-rt-caller-1.png
  go-plugin/doc/images/fusing-server-config-rt-caller-2.png
  go-plugin/doc/images/fusing-theory.png
  go-plugin/doc/images/governance-key-fault-inject.png
  go-plugin/doc/images/governance-key-fusing.png
  go-plugin/doc/images/governance-key-match.png
  go-plugin/doc/images/governance-key-ratelimit.png
  go-plugin/doc/images/governance-key-route.png
  go-plugin/doc/images/ratelimit-client-config-1.png
  go-plugin/doc/images/ratelimit-client-config-2.png
  go-plugin/doc/images/ratelimit-client-config-concurrent-caller.png
  go-plugin/doc/images/ratelimit-client-config-concurrent.png
  go-plugin/doc/images/ratelimit-config.png
  go-plugin/doc/images/ratelimit-server-config-1.png
  go-plugin/doc/images/ratelimit-server-config-2.png
  go-plugin/doc/images/ratelimit-service-config-caller.png
  go-plugin/doc/images/ratelimit-theory.png
  go-plugin/doc/images/ratelimt-client-config-caller.png
  go-plugin/doc/images/route-config-1.png
  go-plugin/doc/images/route-config-2.png
  go-plugin/doc/images/route-multi-destnation-caller.png
  go-plugin/doc/images/route-multi-destnation.png
  go-plugin/doc/images/route-theory-1.png
  go-plugin/doc/images/route-theory-2.png
  go-plugin/doc/images/route-version-2.png
  go-plugin/doc/images/route-version-caller-1.png
  go-plugin/doc/images/route-version-caller-2.png
  go-plugin/doc/images/route-version.png
Labels: cla:yes, size/XL

#117 Master cloud hijack
  go-plugin/configs/codecs/http/egress_http.json
  go-plugin/configs/codecs/http/ingress_http.json
  go-plugin/configs/transcoders/bolt2springcloud/egress_config.json
  go-plugin/configs/transcoders/dubbo2springcloud/egress_config.json
  go-plugin/configs/transcoders/springcloud2dubbo/egress_config.json
  go-plugin/configs/transcoders/xr2springcloud/egress_config.json
  go-plugin/doc/2.6.2bolt2springcloud.md
  go-plugin/doc/2.6.3xml2springcloud.md
  go-plugin/doc/2.6transcoder.md
  go-plugin/doc/api/4.transfer.md
  go-plugin/etc/ant/env_conf
Labels: cla:yes, size/M

#112 Fix plugin commit
  go-plugin/Makefile
  go-plugin/configs/codecs/bolt/egress_bolt.json
  go-plugin/configs/codecs/bolt/ingress_bolt.json
  go-plugin/configs/codecs/dubbo/egress_dubbo.json
  go-plugin/configs/codecs/dubbo/ingress_dubbo.json
  go-plugin/configs/codecs/springcloud/egress_springcloud.json
  go-plugin/configs/codecs/springcloud/ingress_springcloud.json
  go-plugin/configs/codecs/xr/egress_xr.json
  go-plugin/configs/codecs/xr/ingress_xr.json
  go-plugin/etc/script/compile-codec.sh
  go-plugin/etc/script/compile-filter.sh
  go-plugin/etc/script/compile-transcoder.sh
  go-plugin/etc/script/compile.sh
  go-plugin/pkg/config/context.go
Labels: bug, cla:yes, size/L
