Repository mosn/extensions, pull requests merged in 2022-06, with the labels that each got.

#126 http client
  java-quickstart/java-plugin-quickstart/ehttp-client/pom.xml
  java-quickstart/java-plugin-quickstart/ehttp-client/src/main/java/com/alipay/plugin/HttpClientBootstrap.java
  java-quickstart/java-plugin-quickstart/ehttp-client/src/main/java/com/alipay/plugin/HttpRestController.java
  java-quickstart/java-plugin-quickstart/ehttp-client/src/main/java/com/alipay/plugin/RestTemplateBean.java
  java-quickstart/java-plugin-quickstart/ehttp-client/src/main/resources/application.properties
  java-quickstart/java-plugin-quickstart/pom.xml
Labels: cla:yes, size/L

#127 add userinfo
  java-quickstart/java-plugin-quickstart/ehttp-client/src/main/java/com/alipay/plugin/HttpRestController.java
Labels: cla:yes, size/S

#121 feat: update config-api
  go-plugin/doc/api/3.config-api.md
  go-plugin/plugins/stream_filters/dynamic_conf/main/filter.go
Labels: cla:yes, size/M

#120 feat: support logger
  go-plugin/configs/stream_filters/logger/egress_config.json
  go-plugin/configs/stream_filters/logger/ingress_config.json
  go-plugin/configs/stream_filters/logger/metadata.json
  go-plugin/go.mod
  go-plugin/go.sum
  go-plugin/plugins/stream_filters/logger/main/filter.go
  go-plugin/plugins/stream_filters/logger/main/filter_factory.go
  go-plugin/plugins/stream_filters/logger/main/logger.go
  go-plugin/plugins/stream_filters/logger/main/simplelog.go
  go-plugin/plugins/stream_filters/logger/main/tags.go
Labels: cla:yes, size/L

#108 Update images
  go-plugin/Makefile
  go-plugin/build/image/Dockerfile
  go-plugin/etc/ant/env_conf
  go-plugin/etc/ant/start.sh
  go-plugin/go.mod
  go-plugin/go.sum
  go-plugin/pkg/protocol/bolt/mapping_test.go
  go-plugin/pkg/protocol/dubbo/api_test.go
  go-plugin/pkg/protocol/dubbo/decoder.go
  go-plugin/plugins/transcoders/springcloud2dubbo/main/springcloud2dubbo.go
Labels: cla:yes, size/M

#129 fix delve version
  go-plugin/build/image/Dockerfile
Labels: bug, cla:yes, size/XS
