Repository mosn/extensions, pull requests merged in 2022-02, with the labels that each got.

#55 support filter doc.
  go-plugin/configs/stream_filters/auth/ingress_config.json
  go-plugin/doc/2.5filter.md
Labels: cla:yes, size/L

#56 update directory.
  go-plugin/README.md
Labels: cla:yes, size/XS

#57 fix release read lock.
  go-plugin/pkg/common/safe/hashmap.go
Labels: bug, cla:yes, size/XS

#58 add pub pod doc.
  go-plugin/README.md
  go-plugin/doc/3.1pub-pod.md
  go-plugin/doc/3.2plugin-manager.md
Labels: cla:yes, size/L

#60 feat: bolt control
  go-plugin/configs/codecs/bolt/egress_bolt.json
  go-plugin/configs/codecs/bolt/ingress_bolt.json
  go-plugin/configs/codecs/bolt/metadata.json
Labels: cla:yes, size/M

#61 Control
  go-plugin/configs/codecs/bolt/metadata.json
  go-plugin/configs/codecs/dubbo/egress_dubbo.json
  go-plugin/configs/codecs/dubbo/ingress_dubbo.json
  go-plugin/configs/codecs/dubbo/metadata.json
  go-plugin/configs/codecs/springcloud/egress_springcloud.json
  go-plugin/configs/codecs/springcloud/ingress_springcloud.json
  go-plugin/configs/codecs/springcloud/metadata.json
Labels: cla:yes, size/M

#62 prepare beijing workspace.
  go-plugin/configs/codecs/bolt/egress_bolt.json
  go-plugin/configs/codecs/bolt/ingress_bolt.json
  go-plugin/configs/codecs/bolt/metadata.json
  go-plugin/configs/codecs/bolt/mosn_config.json
  go-plugin/configs/codecs/dubbo/egress_dubbo.json
  go-plugin/configs/codecs/dubbo/ingress_dubbo.json
  go-plugin/configs/codecs/dubbo/metadata.json
  go-plugin/configs/codecs/dubbo/mosn_config.json
  go-plugin/configs/stream_filters/auth/ingress_config.json
  go-plugin/configs/stream_filters/auth/metadata.json
  go-plugin/configs/stream_filters/auth/mosn_config.json
  go-plugin/configs/transcoders/bolt2springcloud/egress_config.json
  go-plugin/configs/transcoders/bolt2springcloud/metadata.json
  go-plugin/configs/transcoders/dubbo2springcloud/egress_config.json
  go-plugin/configs/transcoders/dubbo2springcloud/metadata.json
  go-plugin/configs/transcoders/springcloud2dubbo/egress_config.json
  go-plugin/configs/transcoders/springcloud2dubbo/metadata.json
  go-plugin/go.mod
  go-plugin/go.sum
  go-plugin/pkg/protocol/bolt/api.go
  go-plugin/pkg/protocol/bolt/api_test.go
  go-plugin/pkg/protocol/bolt/command.go
  go-plugin/pkg/protocol/bolt/decoder.go
  go-plugin/pkg/protocol/bolt/encoder.go
  go-plugin/pkg/protocol/bolt/header_set_override_test.go
  go-plugin/pkg/protocol/bolt/mapping.go
  go-plugin/pkg/protocol/bolt/mapping_test.go
  go-plugin/pkg/protocol/bolt/matcher.go
  go-plugin/pkg/protocol/bolt/matcher_test.go
  go-plugin/pkg/protocol/bolt/protocol.go
  go-plugin/pkg/protocol/bolt/protocol_test.go
  go-plugin/pkg/protocol/bolt/types.go
  go-plugin/pkg/protocol/dubbo/api.go
  go-plugin/pkg/protocol/dubbo/api_test.go
  go-plugin/pkg/protocol/dubbo/command.go
  go-plugin/pkg/protocol/dubbo/command_test.go
  go-plugin/pkg/protocol/dubbo/decoder.go
  go-plugin/pkg/protocol/dubbo/decoder_test.go
  go-plugin/pkg/protocol/dubbo/encoder.go
  go-plugin/pkg/protocol/dubbo/header.go
  go-plugin/pkg/protocol/dubbo/mapping.go
  go-plugin/pkg/protocol/dubbo/matcher.go
  go-plugin/pkg/protocol/dubbo/protocol.go
  go-plugin/pkg/protocol/dubbo/protocol_test.go
  go-plugin/pkg/protocol/dubbo/types.go
  go-plugin/plugins/codecs/bolt/main/codec.go
  go-plugin/plugins/codecs/dubbo/VERSION
  go-plugin/plugins/codecs/dubbo/main/codec.go
  go-plugin/plugins/stream_filters/auth/VERSION
  go-plugin/plugins/stream_filters/auth/main/auth.go
  go-plugin/plugins/transcoders/bolt2springcloud/VERSION
  go-plugin/plugins/transcoders/bolt2springcloud/main/bolt2sp.go
  go-plugin/plugins/transcoders/bolt2springcloud/main/bolt2sp_test.go
  go-plugin/plugins/transcoders/dubbo2springcloud/VERSION
  go-plugin/plugins/transcoders/dubbo2springcloud/main/dubbo2sp.go
  go-plugin/plugins/transcoders/springcloud2dubbo/VERSION
  go-plugin/plugins/transcoders/springcloud2dubbo/main/sp2dubbo.go
Labels: cla:yes, size/XXL
