Repository mosn/extensions, pull requests merged in 2022-01, with the labels that each got.

#31 fix package directory name.
  go-plugin/etc/script/package-codec.sh
  go-plugin/etc/script/package-filter.sh
  go-plugin/etc/script/package-transcoder.sh
Labels: bug, cla:yes, size/S

#33 feat: fix bug
  go-plugin/pkg/protocol/dubbo/decoder.go
Labels: bug, cla:yes, size/S

#36 update plugin prepare doc
  go-plugin/doc/1.plugin-prepare.md
Labels: cla:yes, size/XS

#37 适配最新代码
  go-plugin/configs/codecs/bolt/egress_bolt.json
  go-plugin/configs/codecs/bolt/ingress_bolt.json
  go-plugin/configs/codecs/dubbo/egress_dubbo.json
  go-plugin/configs/codecs/dubbo/ingress_dubbo.json
  go-plugin/configs/codecs/sp/egress_sp.json
  go-plugin/configs/codecs/sp/ingress_sp.json
  go-plugin/configs/codecs/xr/egress_xr.json
  go-plugin/configs/codecs/xr/ingress_xr.json
  go-plugin/etc/ant/start.sh
  go-plugin/go.mod
  go-plugin/go.sum
  go-plugin/pkg/protocol/dubbo/common/cloud_util.go
  go-plugin/pkg/protocol/dubbo/constants/alipay_router_constants.go
  go-plugin/pkg/protocol/dubbo/govern_util/govern_utils.go
  go-plugin/pkg/protocol/dubbo/govern_util/key.go
  go-plugin/vendor/github.com/valyala/fasthttp/.gitignore
  go-plugin/vendor/github.com/valyala/fasthttp/README.md
  go-plugin/vendor/github.com/valyala/fasthttp/args.go
  go-plugin/vendor/github.com/valyala/fasthttp/bytesconv.go
  go-plugin/vendor/github.com/valyala/fasthttp/bytesconv_32.go
  go-plugin/vendor/github.com/valyala/fasthttp/bytesconv_64.go
  go-plugin/vendor/github.com/valyala/fasthttp/client.go
  go-plugin/vendor/github.com/valyala/fasthttp/cookie.go
  go-plugin/vendor/github.com/valyala/fasthttp/go.mod
  go-plugin/vendor/github.com/valyala/fasthttp/go.sum
  go-plugin/vendor/github.com/valyala/fasthttp/header.go
  go-plugin/vendor/github.com/valyala/fasthttp/http.go
  go-plugin/vendor/github.com/valyala/fasthttp/server.go
  go-plugin/vendor/github.com/valyala/fasthttp/status.go
  go-plugin/vendor/github.com/valyala/fasthttp/strings.go
  go-plugin/vendor/github.com/valyala/fasthttp/tcpdialer.go
  go-plugin/vendor/github.com/valyala/fasthttp/uri.go
  go-plugin/vendor/github.com/valyala/fasthttp/uri_unix.go
  go-plugin/vendor/github.com/valyala/fasthttp/uri_windows.go
  go-plugin/vendor/github.com/valyala/fasthttp/userdata.go
  go-plugin/vendor/modules.txt
Labels: cla:yes, size/XL

#41 feat: fix bug
  go-plugin/configs/codecs/dubbo/metadata.json
  go-plugin/etc/ant/start.sh
  go-plugin/plugins/codecs/xr/main/codec.go
  go-plugin/vendor/github.com/valyala/fasthttp/.gitignore
  go-plugin/vendor/github.com/valyala/fasthttp/README.md
  go-plugin/vendor/github.com/valyala/fasthttp/args.go
  go-plugin/vendor/github.com/valyala/fasthttp/bytesconv.go
  go-plugin/vendor/github.com/valyala/fasthttp/bytesconv_32.go
  go-plugin/vendor/github.com/valyala/fasthttp/bytesconv_64.go
  go-plugin/vendor/github.com/valyala/fasthttp/client.go
  go-plugin/vendor/github.com/valyala/fasthttp/cookie.go
  go-plugin/vendor/github.com/valyala/fasthttp/go.mod
  go-plugin/vendor/github.com/valyala/fasthttp/go.sum
  go-plugin/vendor/github.com/valyala/fasthttp/header.go
  go-plugin/vendor/github.com/valyala/fasthttp/http.go
  go-plugin/vendor/github.com/valyala/fasthttp/server.go
  go-plugin/vendor/github.com/valyala/fasthttp/status.go
  go-plugin/vendor/github.com/valyala/fasthttp/strings.go
  go-plugin/vendor/github.com/valyala/fasthttp/tcpdialer.go
  go-plugin/vendor/github.com/valyala/fasthttp/uri.go
  go-plugin/vendor/github.com/valyala/fasthttp/uri_unix.go
  go-plugin/vendor/github.com/valyala/fasthttp/uri_windows.go
  go-plugin/vendor/github.com/valyala/fasthttp/userdata.go
Labels: bug, cla:yes, size/XXL

#42 fix typo
  go-plugin/doc/2.1bolt.md
Labels: bug, cla:yes, size/M

#43 change sp to springcloud.
  go-plugin/configs/codecs/springcloud/egress_springcloud.json
  go-plugin/configs/codecs/springcloud/ingress_springcloud.json
  go-plugin/configs/codecs/springcloud/metadata.json
  go-plugin/doc/1.plugin-prepare.md
  go-plugin/plugins/codecs/springcloud/main/codec.go
Labels: cla:yes, size/M

#45 add dubbo doc
  go-plugin/doc/2.2dubbo.md
  go-plugin/doc/images/dubbo_protocol_header.png
Labels: cla:yes, size/L

#46 update readme.
  go-plugin/README.md
  go-plugin/doc/2.2dubbo.md
Labels: cla:yes, size/M

#47 modify dubbo dubbo2springcloud springcloud2dubbo
  go-plugin/configs/transcoders/dubbo2springcloud/egress_config.json
  go-plugin/configs/transcoders/dubbo2springcloud/metadata.json
  go-plugin/configs/transcoders/springcloud2dubbo/egress_config.json
  go-plugin/configs/transcoders/springcloud2dubbo/metadata.json
  go-plugin/pkg/protocol/dubbo/common/cloud_util.go
  go-plugin/pkg/protocol/dubbo/constants/alipay_router_constants.go
  go-plugin/pkg/protocol/dubbo/govern_util/govern_utils.go
  go-plugin/pkg/protocol/dubbo/govern_util/key.go
  go-plugin/plugins/transcoders/dubbo2springcloud/VERSION
  go-plugin/plugins/transcoders/dubbo2springcloud/main/dubbo2springcloud.go
  go-plugin/plugins/transcoders/springcloud2dubbo/VERSION
  go-plugin/plugins/transcoders/springcloud2dubbo/main/springcloud2dubbo.go
Labels: cla:yes, size/L

#48 add springcloud doc.
  go-plugin/.gitignore
  go-plugin/configs/codecs/springcloud/egress_springcloud.json
  go-plugin/configs/codecs/springcloud/ingress_springcloud.json
  go-plugin/configs/stream_filters/springcloud_header/egress_config.json
  go-plugin/configs/stream_filters/springcloud_header/ingress_config.json
  go-plugin/configs/stream_filters/springcloud_header/metadata.json
  go-plugin/doc/2.2dubbo.md
  go-plugin/doc/2.3xml.md
  go-plugin/doc/2.4springcloud.md
  go-plugin/plugins/stream_filters/springcloud_header/main/springcloud_header.go
Labels: cla:yes, size/L

#49 update spring cloud readme.
  README.md
  go-plugin/README.md
  go-plugin/doc/1.plugin-prepare.md
  go-plugin/doc/2.1bolt.md
  go-plugin/doc/2.2dubbo.md
  go-plugin/doc/2.4springcloud.md
Labels: cla:yes, size/M

#52 增加协议转换文档
  go-plugin/configs/transcoders/bolt2springcloud/egress_config.json
  go-plugin/doc/2.6.2bolt2springcloud.md
  go-plugin/doc/images/bolt-append.jpg
  go-plugin/doc/images/bolt-client-debug.png
  go-plugin/doc/images/bolt-header-transfer.png
  go-plugin/doc/images/bolt-request-transfer.jpg
  go-plugin/doc/images/bolt2springcloud.jpg
  go-plugin/doc/images/mosn-bolt-debug.jpg
  go-plugin/doc/images/springcloud-server-debug.png
  go-plugin/plugins/transcoders/bolt2springcloud/main/bolt2sp.go
  go-plugin/plugins/transcoders/dubbo2springcloud/main/dubbo2springcloud.go
Labels: cla:yes, size/L

#53 add xr doc.
  go-plugin/doc/2.1bolt.md
  go-plugin/doc/2.3xml.md
  go-plugin/etc/ant/start.sh
  go-plugin/go.mod
  go-plugin/go.sum
  go-plugin/pkg/protocol/xr/api.go
  go-plugin/pkg/protocol/xr/decode.go
  go-plugin/pkg/protocol/xr/encode.go
  go-plugin/pkg/protocol/xr/protocol.go
  go-plugin/pkg/protocol/xr/types.go
  go-plugin/plugins/codecs/xr/main/codec.go
  go-plugin/plugins/transcoders/dubbo2springcloud/main/dubbo2sp.go
  go-plugin/plugins/transcoders/springcloud2dubbo/main/sp2dubbo.go
Labels: cla:yes, size/L

#54 Xml doc
  go-plugin/README.md
  go-plugin/doc/2.3xml.md
Labels: cla:yes, size/M
