Repository mosn/extensions, pull requests merged in 2022-04, with the labels that each got.

#95 add protocol api doc
  go-plugin/README.md
  go-plugin/doc/api/1. xprotocol-api.md
  go-plugin/doc/api/README.md
  go-plugin/plugins/codecs/bolt/main/codec.go
Labels: cla:yes, size/XL

#96 add protocol api doc
  go-plugin/README.md
  go-plugin/doc/api/README.md
Labels: cla:yes, size/S

#94 Xr2sp
  go-plugin/configs/transcoders/xr2springcloud/egress_config.json
  go-plugin/configs/transcoders/xr2springcloud/pub_sub.sh
  go-plugin/configs/transcoders/xr2springcloud/request.sh
  go-plugin/etc/ant/env_conf
  go-plugin/plugins/transcoders/xr2springcloud/main/config.go
  go-plugin/plugins/transcoders/xr2springcloud/main/xr2sp.go
Labels: cla:yes, size/L

#97 support apple m1.
  go-plugin/Makefile
  go-plugin/etc/ant/start.sh
  go-plugin/etc/script/start.sh
Labels: cla:yes, size/S

#98 support multiple platform(arm64/amd64/i386), optimize debugging and r…
  go-plugin/Makefile
  go-plugin/build/image/Dockerfile
  go-plugin/configs/codecs/bolt/mosn_config.json
  go-plugin/configs/internal/base_conf/listeners/sofarpc/virtual_inbound.json
  go-plugin/configs/internal/base_conf/listeners/sofarpc/virtual_outbound.json
  go-plugin/configs/internal/base_conf/mosn_config.json
  go-plugin/configs/internal/base_conf/routers/egress_tp_http1_router/http.json
  go-plugin/configs/internal/base_conf/routers/ingress_tp_http1_router/http.json
  go-plugin/doc/1.plugin-prepare.md
  go-plugin/etc/ant/env_conf
  go-plugin/etc/ant/run.sh
  go-plugin/etc/ant/start.sh
  go-plugin/etc/script/compile-codec.sh
  go-plugin/etc/script/compile-filter.sh
  go-plugin/etc/script/compile-transcoder.sh
  go-plugin/etc/script/compile.sh
  go-plugin/etc/script/package-codec.sh
  go-plugin/etc/script/package-filter.sh
  go-plugin/etc/script/package-transcoder.sh
  go-plugin/etc/script/start.sh
Labels: cla:yes, size/XL

#99 build amd64 plugin if detect m1 chip.
  go-plugin/Makefile
  go-plugin/doc/1.plugin-prepare.md
Labels: cla:yes, size/M

#100 Update doc
  go-plugin/.gitignore
  go-plugin/configs/transcoders/bolt2springcloud/egress_config.json
  go-plugin/configs/transcoders/bolt2springcloud/pub_sub.sh
  go-plugin/configs/transcoders/dubbo2springcloud/egress_config.json
  go-plugin/configs/transcoders/springcloud2dubbo/egress_config.json
  go-plugin/configs/transcoders/xr2springcloud/egress_config.json
  go-plugin/configs/transcoders/xr2springcloud/pub_sub.sh
  go-plugin/doc/2.6.1dubbo2springcloud.md
  go-plugin/doc/2.6.2bolt2springcloud.md
  go-plugin/doc/2.6.3xml2springcloud.md
  go-plugin/doc/2.6transcoder.md
  go-plugin/doc/2.7.2transcoder.md
  go-plugin/doc/2.7FAQ.md
  go-plugin/doc/api/3.config-api.md
  go-plugin/doc/images/bolt-header-transfer.png
  go-plugin/doc/images/bolt-request-transfer.jpg
  go-plugin/doc/images/dubbo_springcloud_transcoder.jpg
  go-plugin/doc/images/dubbo_sub.jpg
  go-plugin/doc/images/dynamic_conf.jpg
  go-plugin/doc/images/http_pub.jpg
  go-plugin/doc/images/reservation-service-application.png
  go-plugin/doc/images/springcloud-dubbo.png
  go-plugin/doc/images/springcloud-server-debug.png
  go-plugin/doc/images/transfer_rule.jpg
  go-plugin/doc/images/upload_transcoder.jpg
  go-plugin/etc/ant/env_conf
  go-plugin/pkg/config/dynamic.go
  go-plugin/plugins/stream_filters/auth/main/auth.go
Labels: cla:yes, size/XL

#101 fix xr decode error.
  go-plugin/pkg/protocol/xr/command.go
  go-plugin/pkg/protocol/xr/decode.go
  go-plugin/pkg/protocol/xr/encode.go
  go-plugin/pkg/protocol/xr/protocol.go
Labels: bug, cla:yes, size/M

#102 add filter api doc
  go-plugin/doc/api/2. filter-api.md
  go-plugin/doc/api/3.config-api.md
Labels: cla:yes, size/L

#103 add filter api doc
  go-plugin/README.md
  go-plugin/doc/api/README.md
Labels: cla:yes, size/S

#105 update branch info
  go-plugin/doc/1.plugin-prepare.md
Labels: cla:yes, size/XS

#107 Update doc
  go-plugin/README.md
  go-plugin/configs/stream_filters/dynamic_conf/ingress_config.json
  go-plugin/doc/api/README.md
Labels: cla:yes, size/S

#109 docs: update api
  go-plugin/doc/api/README.md
Labels: cla:yes, size/XS
