Repository mosn/extensions, pull requests merged in 2022-03, with the labels that each got.

#65 upgrade module name to mosn.io
  go-plugin/Makefile
  go-plugin/configs/codecs/bolt/mosn_config.json
  go-plugin/configs/codecs/xr/mosn_config.json
  go-plugin/configs/stream_filters/auth/mosn_config.json
  go-plugin/doc/1.plugin-prepare.md
  go-plugin/doc/2.6.2bolt2springcloud.md
  go-plugin/etc/ant/start.sh
  go-plugin/etc/script/start.sh
  go-plugin/go.mod
  go-plugin/pkg/protocol/bolt/command.go
  go-plugin/pkg/protocol/xr/api.go
  go-plugin/pkg/protocol/xr/command.go
  go-plugin/pkg/protocol/xr/decode.go
  go-plugin/pkg/protocol/xr/encode.go
  go-plugin/pkg/protocol/xr/protocol.go
  go-plugin/plugins/codecs/bolt/main/codec.go
  go-plugin/plugins/codecs/dubbo/main/codec.go
  go-plugin/plugins/codecs/xr/main/codec.go
  go-plugin/plugins/transcoders/bolt2springcloud/main/bolt2sp.go
  go-plugin/plugins/transcoders/bolt2springcloud/main/bolt2sp_test.go
  go-plugin/plugins/transcoders/dubbo2springcloud/main/dubbo2sp.go
  go-plugin/plugins/transcoders/springcloud2dubbo/main/sp2dubbo.go
  go-plugin/plugins/transcoders/xr2springcloud/main/xr2sp.go
Labels: cla:yes, size/M

#64 add 2.6transcoder & 2.6.1dubbo2springcloud
  go-plugin/configs/transcoders/dubbo2springcloud/egress_config.json
  go-plugin/doc/2.6.1dubbo2springcloud.md
  go-plugin/doc/2.6transcoder.md
  go-plugin/doc/images/dubbo_springcloud_transcoder.jpg
  go-plugin/doc/images/reservation-service-application.png
  go-plugin/doc/images/springcloud-dubbo.png
Labels: cla:yes, size/L

#71 feat: delete code
  go-plugin/pkg/protocol/bolt/command.go
  go-plugin/plugins/codecs/bolt/main/codec.go
  go-plugin/plugins/codecs/dubbo/main/codec.go
  go-plugin/plugins/transcoders/bolt2springcloud/main/bolt2sp.go
  go-plugin/plugins/transcoders/bolt2springcloud/main/bolt2sp_test.go
  go-plugin/plugins/transcoders/dubbo2springcloud/main/dubbo2sp.go
  go-plugin/plugins/transcoders/springcloud2dubbo/main/sp2dubbo.go
Labels: cla:yes, size/XXL

#72 feat: delete codec
  go-plugin/configs/codecs/bolt/metadata.json
  go-plugin/configs/codecs/bolt/mosn_config.json
  go-plugin/configs/codecs/dubbo/egress_dubbo.json
  go-plugin/configs/codecs/dubbo/ingress_dubbo.json
  go-plugin/configs/codecs/dubbo/metadata.json
  go-plugin/configs/stream_filters/auth/mosn_config.json
  go-plugin/configs/transcoders/dubbo2springcloud/egress_config.json
Labels: cla:yes, size/L

#73 Bank beijing
  go-plugin/Makefile
  go-plugin/configs/codecs/beis/beis_req.txt
  go-plugin/configs/codecs/beis/egress_beis.json
  go-plugin/configs/codecs/beis/ingress_beis.json
  go-plugin/configs/codecs/beis/metadata.json
  go-plugin/configs/codecs/beis/pub_sub.sh
  go-plugin/configs/codecs/beis/request_beis.sh
  go-plugin/configs/codecs/cd/cd_req.txt
  go-plugin/configs/codecs/cd/egress_cd.json
  go-plugin/configs/codecs/cd/ingress_cd.json
  go-plugin/configs/codecs/cd/metadata.json
  go-plugin/configs/codecs/cd/pub_sub.sh
  go-plugin/configs/codecs/cd/request_cd.sh
  go-plugin/configs/codecs/xr/mosn_config.json
  go-plugin/configs/codecs/xr/request.sh
  go-plugin/doc/1.plugin-prepare.md
  go-plugin/doc/2.6.2bolt2springcloud.md
  go-plugin/etc/ant/env_conf
  go-plugin/etc/ant/start.sh
  go-plugin/etc/script/start.sh
  go-plugin/go.mod
  go-plugin/go.sum
  go-plugin/pkg/protocol/beis/api.go
  go-plugin/pkg/protocol/beis/command.go
  go-plugin/pkg/protocol/beis/decode.go
  go-plugin/pkg/protocol/beis/decode_head_test.go
  go-plugin/pkg/protocol/beis/encode.go
  go-plugin/pkg/protocol/beis/mapping.go
  go-plugin/pkg/protocol/beis/matcher.go
  go-plugin/pkg/protocol/beis/protocol.go
  go-plugin/pkg/protocol/beis/types.go
  go-plugin/pkg/protocol/cd/api.go
  go-plugin/pkg/protocol/cd/command.go
  go-plugin/pkg/protocol/cd/decode.go
  go-plugin/pkg/protocol/cd/decode_head_test.go
  go-plugin/pkg/protocol/cd/encode.go
  go-plugin/pkg/protocol/cd/mapping.go
  go-plugin/pkg/protocol/cd/matcher.go
  go-plugin/pkg/protocol/cd/protocol.go
  go-plugin/pkg/protocol/cd/types.go
  go-plugin/pkg/protocol/xr/buffer.go
  go-plugin/pkg/protocol/xr/encode.go
  go-plugin/pkg/protocol/xr/protocol.go
  go-plugin/pkg/protocol/xr/types.go
  go-plugin/plugins/codecs/beis/main/codec.go
  go-plugin/plugins/codecs/cd/VERSION
  go-plugin/plugins/codecs/cd/main/codec.go
  go-plugin/plugins/transcoders/xr2springcloud/main/xr2sp.go
Labels: cla:yes, size/XXL

#75 fix cd invoke failed and update comments.
  go-plugin/configs/codecs/beis/request_beis.sh
  go-plugin/configs/codecs/cd/request_cd.sh
  go-plugin/etc/ant/start.sh
  go-plugin/pkg/protocol/beis/protocol.go
  go-plugin/pkg/protocol/cd/decode.go
  go-plugin/pkg/protocol/cd/encode.go
  go-plugin/pkg/protocol/cd/protocol.go
  go-plugin/pkg/protocol/cd/types.go
Labels: bug, cla:yes, size/M

#76 fix query ip address.
  go-plugin/etc/ant/start.sh
Labels: bug, cla:yes, size/XS

#80 support for non-debug startup mode
  go-plugin/Makefile
  go-plugin/doc/1.plugin-prepare.md
  go-plugin/etc/ant/run.sh
  go-plugin/etc/ant/start.sh
Labels: cla:yes, size/S

#79 remove mapping go path and add go proxy.
  go-plugin/Makefile
  go-plugin/etc/script/compile-codec.sh
  go-plugin/etc/script/compile-filter.sh
  go-plugin/etc/script/compile-transcoder.sh
Labels: cla:yes, size/S

#81 sync master
  go-plugin/Makefile
  go-plugin/doc/1.plugin-prepare.md
  go-plugin/etc/ant/run.sh
  go-plugin/etc/ant/start.sh
  go-plugin/etc/script/compile-codec.sh
  go-plugin/etc/script/compile-filter.sh
  go-plugin/etc/script/compile-transcoder.sh
Labels: cla:yes, size/M

#83 feat: modify makefile & add go/mod
  go-plugin/Makefile
  go-plugin/etc/ant/start.sh
Labels: cla:yes, size/XS

#86 Bank beijing
  go-plugin/Makefile
  go-plugin/etc/ant/start.sh
Labels: cla:yes, size/XS

#82 Bj bank encrypt & decrypt
  go-plugin/configs/codecs/beis/beis_req_private.txt
  go-plugin/configs/codecs/beis/request_beis_private.sh
  go-plugin/configs/codecs/bums/egress_bums.json
  go-plugin/configs/codecs/bums/ingress_bums.json
  go-plugin/configs/codecs/bums/metadata.json
  go-plugin/configs/codecs/bums/pub_sub.sh
  go-plugin/configs/codecs/bums/req.txt
  go-plugin/configs/codecs/bums/request.sh
  go-plugin/configs/stream_filters/bums_decoder/egress_config.json
  go-plugin/configs/stream_filters/bums_decoder/ingress_config.json
  go-plugin/configs/stream_filters/bums_decoder/metadata.json
  go-plugin/configs/stream_filters/bums_encoder/egress_config.json
  go-plugin/configs/stream_filters/bums_encoder/ingress_config.json
  go-plugin/configs/stream_filters/bums_encoder/metadata.json
  go-plugin/etc/ant/start.sh
  go-plugin/go.mod
  go-plugin/pkg/common/encryption/base64_tools.go
  go-plugin/pkg/common/encryption/base64_tools_test.go
  go-plugin/pkg/common/encryption/secret_parser.go
  go-plugin/pkg/common/encryption/secret_parser_test.go
  go-plugin/pkg/common/encryption/xor.go
  go-plugin/pkg/common/encryption/xor/utils.go
  go-plugin/pkg/common/encryption/xor_test.go
  go-plugin/pkg/common/header_utils.go
  go-plugin/pkg/protocol/beis/encode.go
  go-plugin/pkg/protocol/beis/protocol.go
  go-plugin/plugins/codecs/bums/VERSION
  go-plugin/plugins/codecs/bums/main/bums.go
  go-plugin/plugins/stream_filters/bums_decoder/main/bums.go
  go-plugin/plugins/stream_filters/bums_encoder/main/bums.go
Labels: cla:yes, size/XXL

#87 update directory
  go-plugin/README.md
  go-plugin/doc/2.6.1dubbo2springcloud.md
  go-plugin/doc/2.6.2bolt2springcloud.md
  go-plugin/doc/2.6transcoder.md
Labels: cla:yes, size/L

#89 add pub bash.
  go-plugin/configs/codecs/xr/pub_sub.sh
Labels: cla:yes, size/XS

#91 optimize compile plugin
  go-plugin/Makefile
  go-plugin/doc/1.plugin-prepare.md
  go-plugin/etc/script/compile-codec.sh
Labels: cla:yes, size/M

#90 feat: modify bolt2springcloud config
  go-plugin/configs/transcoders/bolt2springcloud/egress_config.json
  go-plugin/configs/transcoders/bolt2springcloud/pub_sub.sh
  go-plugin/etc/ant/env_conf
  go-plugin/plugins/transcoders/bolt2springcloud/main/bolt2sp.go
  go-plugin/plugins/transcoders/bolt2springcloud/main/bolt2sp_test.go
  go-plugin/plugins/transcoders/bolt2springcloud/main/bolt2springcloud.go
  go-plugin/plugins/transcoders/bolt2springcloud/main/config.go
Labels: cla:yes, size/L
